# Generated by Django 3.0.8 on 2021-05-22 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databases', '0005_remove_database_project'),
        ('projects', '0012_projectconfiguration_database'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
                ('invitation_code', models.UUIDField(default=uuid.uuid4)),
                ('databases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_databases', to='databases.Database')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_projects', to='projects.Project')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
