# Generated by Django 3.0.8 on 2021-05-23 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectconfiguration_database'),
        ('databases', '0005_remove_database_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='databases',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_databases', to='databases.Database'),
        ),
        migrations.AlterField(
            model_name='group',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_projects', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_databases', to=settings.AUTH_USER_MODEL),
        ),
    ]
