# Generated by Django 3.0.8 on 2021-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210523_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-updated_at']},
        ),
    ]
