# Generated by Django 3.0.8 on 2021-05-24 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_auto_20210523_1439'),
        ('projects', '0013_auto_20210523_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_auto_20210523_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='databases',
        ),
        migrations.AddField(
            model_name='group',
            name='databases',
            field=models.ManyToManyField(related_name='group_databases', to='databases.Database'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='projects',
        ),
        migrations.AddField(
            model_name='group',
            name='projects',
            field=models.ManyToManyField(related_name='group_projects', to='projects.Project'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='users',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='group_databases', to=settings.AUTH_USER_MODEL),
        ),
    ]
