# Generated by Django 3.0.8 on 2021-05-19 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_auto_20210519_1752'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databases', '0003_auto_20210515_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrain',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('scheduled_every', models.IntegerField(choices=[(5, 5), (7, 7), (14, 14), (31, 31)], null=True)),
                ('task_id', models.UUIDField(default=uuid.uuid4)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_retrain', to='databases.Database')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_retrain', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_retrain', to='projects.Project')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
