# Generated by Django 3.0.8 on 2021-05-22 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retrains', '0002_auto_20210522_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrain',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_retrain', to=settings.AUTH_USER_MODEL),
        ),
    ]
