# Generated by Django 3.0.8 on 2021-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrains', '0003_auto_20210522_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retrain',
            options={'ordering': ['-updated_at']},
        ),
    ]
