# Generated by Django 3.0.8 on 2021-05-03 19:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(default='Mi proyecto', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectConfiguration',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('Clasificación', 'Clasificación'), ('Regresión', 'Regresión')], default='Regresión', max_length=40)),
                ('trained', models.BooleanField(default=False)),
                ('last_time_trained', models.DateTimeField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('training_task_id', models.UUIDField(blank=True, null=True)),
                ('training_task_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Empezada', 'Empezada'), ('Reintentando', 'Reintentando'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado'), ('Recibido', 'Recibido'), ('Fallida', 'Fallida')], default='Pendiente', max_length=40)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_configuration', to='projects.Project')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectConfigFile',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('all_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=None)),
                ('saved_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=None)),
                ('deleted_columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, size=None)),
                ('final_data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('label', models.CharField(max_length=200)),
                ('project_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_file', to='projects.ProjectConfiguration')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
