# Generated by Django 3.0.8 on 2021-05-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='temporary_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='unfinished',
            field=models.BooleanField(default=True),
        ),
    ]
