# Generated by Django 3.1.7 on 2021-03-29 23:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210329_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfigfile',
            name='all_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='projectconfigfile',
            name='deleted_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='projectconfigfile',
            name='saved_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
