# Generated by Django 3.1.7 on 2021-03-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectconfigfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectconfigfile',
            old_name='project_configuration',
            new_name='configuration_file',
        ),
    ]
