# Generated by Django 3.0.8 on 2021-05-07 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210507_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='temporary_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
