# Generated by Django 3.0.8 on 2021-05-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210507_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='temporary_uuid',
        ),
    ]
