# Generated by Django 3.0.8 on 2021-05-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_temporary_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='unfinished',
        ),
    ]
