# Generated by Django 3.0.8 on 2021-05-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfiguration',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_configuration', to='projects.Project'),
        ),
    ]
