# Generated by Django 3.1.7 on 2021-03-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210329_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectconfigfile',
            old_name='configuration_file',
            new_name='project_configuration',
        ),
    ]
