# Generated by Django 3.1.7 on 2021-03-30 00:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210329_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfigfile',
            name='final_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
