# Generated by Django 3.1.7 on 2021-03-30 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210330_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconfigfile',
            name='final_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=8), size=8),
        ),
    ]
