# Generated by Django 3.0.8 on 2021-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210515_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='configured_scheduled_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='created_from_database',
            field=models.BooleanField(default=False),
        ),
    ]
