# Generated by Django 3.0.8 on 2021-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210519_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='configured_scheduled_training',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_from_database',
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='configured_scheduled_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='created_from_database',
            field=models.BooleanField(default=False),
        ),
    ]
