# Generated by Django 3.0.8 on 2021-05-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_remove_database_project'),
        ('projects', '0011_auto_20210519_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='database',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_database', to='databases.Database'),
        ),
    ]
