# Generated by Django 3.2 on 2021-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210330_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfiguration',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='error',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
