# Generated by Django 3.0.8 on 2021-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectconfiguration_database'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='projectconfigfile',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='projectconfiguration',
            options={'ordering': ['-updated_at']},
        ),
    ]
