# Generated by Django 3.2 on 2021-04-25 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210422_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='projectconfigfile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='projectconfiguration',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='projectconfigfile',
            name='transformed_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
