# Generated by Django 3.2 on 2021-04-25 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210425_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfigfile',
            name='transformed_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
