# Generated by Django 3.2 on 2021-04-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectconfigfile_transformed_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfigfile',
            name='transformed_data',
        ),
        migrations.RemoveField(
            model_name='projectconfigfile',
            name='transformed_label',
        ),
    ]
