# Generated by Django 3.0.8 on 2021-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210509_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'Trial Account'), (1, 'Basic Account'), (2, 'Premium Account')], default=0),
        ),
    ]
