# Generated by Django 3.0.8 on 2021-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
