# Generated by Django 3.0.8 on 2021-05-12 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('database_name', models.TextField()),
                ('database_host', django_cryptography.fields.encrypt(models.TextField())),
                ('database_port', django_cryptography.fields.encrypt(models.DecimalField(decimal_places=0, max_digits=6))),
                ('database_password', django_cryptography.fields.encrypt(models.TextField())),
                ('database_type', django_cryptography.fields.encrypt(models.TextField(choices=[('postgres', 'Postgres'), ('mysql', 'Mysql')], default='postgres'))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_database', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
