# Generated by Django 3.0.8 on 2021-05-15 13:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_database_database_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='database_type',
            field=django_cryptography.fields.encrypt(models.TextField(choices=[('postgresql', 'Postgres'), ('mysql', 'Mysql')], default='postgresql')),
        ),
    ]
