# Generated by Django 3.0.8 on 2021-05-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210519_1752'),
        ('databases', '0003_auto_20210515_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_database', to='projects.Project'),
        ),
    ]
