# Generated by Django 3.0.8 on 2021-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_remove_database_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['-updated_at']},
        ),
    ]
