# Generated by Django 3.0.8 on 2021-05-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='last_week_average_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='last_week_average_error',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
