# Generated by Django 3.0.8 on 2021-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstats', '0002_auto_20210508_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='average_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='average_error',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_week_average_accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='last_week_average_error',
            field=models.FloatField(default=0.0),
        ),
    ]
