# Generated by Django 3.0.8 on 2021-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstats', '0006_auto_20210509_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectvisits',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='userstats',
            options={'ordering': ['-updated_at']},
        ),
    ]
