# Generated by Django 3.2 on 2021-04-25 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('project_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('features_columns', models.CharField(blank=True, max_length=100, null=True)),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('trained_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
