# Generated by Django 3.0.8 on 2021-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['-updated_at']},
        ),
    ]
